import type { Metadata } from "next";
import MainNavbar from "./components/shared/MainNavbar";
import MainFooter from "./components/shared/MainFooter";


export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <div className="h-screen w-screen relative">
            <MainNavbar />
            {children}
            <MainFooter />
        </div>
    );
}
